"use strict";
const string1 = 'apple';
const string2 = 'orange';
console.log(string1 === string2);
console.log(string1 !== string2);
const mixCase = "Hellow world";
console.log(mixCase.toLowerCase() === "Hellow world");
const num1 = 10;
const num2 = 5;
console.log(num1 === num2);
console.log(num1 !== num2);
console.log(num1 > num2);
console.log(num1 < num2);
console.log(num1 >= num2);
console.log(num1 <= num2);
const condition = true;
const condition2 = false;
console.log(condition && condition2);
console.log(condition || condition2);
const fruit = ['apple', 'mango', 'banana'];
console.log(fruit.includes('banana'));
console.log(fruit.includes('Banana'));
